### ISSUE TITLE
Ventura

### ISSUE THREAD

**Issue by staciax** [leonyaaaaaaa/hackintosh-b550m-pro4#1]
can i update to ventura?

**Comment by leonyaaaaaaa** [comment]
> can i update to ventura?

as for me I don't like Ventura so I didn't bother with it 

if you really want, I think I can give it a try next Saturday

**Comment by staciax** [comment]
I wanna try ventura :-:)
thank you <3

**Comment by staciax** [comment]
I finally got it installed. 

![Uploading 2165CE2A-1474-45DA-AEAB-585AE5E92307.png…]()

**Comment by staciax** [comment]
![Uploading F434A745-7E04-4123-8842-43B56AD3E7C2.png…]()
